env_config:
  prey_count: 2
  prey_speed: 1.0
  prey_view_size: 10
  prey_size: 1
  prey_color: [0, 255, 0]  # Green
  prey_kill_reward: -10
  prey_alive_reward: 0.1
  prey_reward_sqr_reward: 1

  predator_count: 2
  predator_speed: 1.0
  predator_view_size: 10
  predator_size: 1
  predator_color: [255, 0, 0]  # Red
  predator_kill_reward: 10

  map_size: 40
  max_steps: 400
  screen_size: 600
  render_mode: None
  fps: 60

model_config:
  learning_rate: 0.0001
  training_iterations: 100
  num_env_runners: 9
  num_envs_per_env_runner: 8
  train_batch_size_per_learner: 4000
  num_sgd_iter: 30

short_names:
  prey_count: "prc"
  prey_speed: "prsp"
  prey_view_size: "prv"
  prey_size: "prs"
  prey_color: "prco"
  prey_kill_reward: "prkr"
  prey_alive_reward: "prar"
  prey_reward_sqr_reward: "prrr"

  predator_count: "pdc"
  predator_speed: "pdsp"
  predator_view_size: "pdv"
  predator_size: "pds"
  predator_color: "pdco"
  predator_kill_reward: "pdkr"

  map_size: "ms"
  max_steps: "mxs"
  screen_size: "ss"
  render_mode: "rm"
  fps: "fps"

  learning_rate: "lr"
  training_iterations: "ti"
  num_env_runners: "nr"
  num_envs_per_env_runner: 'npr'
  train_batch_size_per_learner: 'bs'
  num_sgd_iter: 'ns'