wandb_version: 1

extra_python_environs_for_driver:
  desc: null
  value: {}
extra_python_environs_for_worker:
  desc: null
  value: {}
placement_strategy:
  desc: null
  value: PACK
num_gpus:
  desc: null
  value: 0
_fake_gpus:
  desc: null
  value: false
num_cpus_for_main_process:
  desc: null
  value: 1
eager_tracing:
  desc: null
  value: true
eager_max_retraces:
  desc: null
  value: 20
tf_session_args:
  desc: null
  value:
    intra_op_parallelism_threads: 2
    inter_op_parallelism_threads: 2
    gpu_options:
      allow_growth: true
    log_device_placement: false
    device_count:
      CPU: 1
    allow_soft_placement: true
local_tf_session_args:
  desc: null
  value:
    intra_op_parallelism_threads: 8
    inter_op_parallelism_threads: 8
torch_compile_learner:
  desc: null
  value: false
torch_compile_learner_what_to_compile:
  desc: null
  value: FORWARD_TRAIN
torch_compile_learner_dynamo_backend:
  desc: null
  value: aot_eager
torch_compile_learner_dynamo_mode:
  desc: null
  value: null
torch_compile_worker:
  desc: null
  value: false
torch_compile_worker_dynamo_backend:
  desc: null
  value: aot_eager
torch_compile_worker_dynamo_mode:
  desc: null
  value: null
enable_rl_module_and_learner:
  desc: null
  value: false
enable_env_runner_and_connector_v2:
  desc: null
  value: false
env:
  desc: null
  value: custom_tag_v0
env_config:
  desc: null
  value:
    num_prey: 2
    num_predators: 2
    prey_speed: 1.2
    predator_speed: 1
    map_size: 30
    max_steps: 200
    screen_size: 600
    prey_view_size: 10
    predator_view_size: 10
observation_space:
  desc: null
  value: null
action_space:
  desc: null
  value: null
clip_rewards:
  desc: null
  value: null
normalize_actions:
  desc: null
  value: true
clip_actions:
  desc: null
  value: true
_is_atari:
  desc: null
  value: null
env_task_fn:
  desc: null
  value: null
render_env:
  desc: null
  value: false
action_mask_key:
  desc: null
  value: action_mask
env_runner_cls:
  desc: null
  value: null
num_env_runners:
  desc: null
  value: 9
num_envs_per_env_runner:
  desc: null
  value: 4
num_cpus_per_env_runner:
  desc: null
  value: 1
num_gpus_per_env_runner:
  desc: null
  value: 0
custom_resources_per_env_runner:
  desc: null
  value: {}
validate_env_runners_after_construction:
  desc: null
  value: true
sample_timeout_s:
  desc: null
  value: 60.0
_env_to_module_connector:
  desc: null
  value: null
add_default_connectors_to_env_to_module_pipeline:
  desc: null
  value: true
_module_to_env_connector:
  desc: null
  value: null
add_default_connectors_to_module_to_env_pipeline:
  desc: null
  value: true
episode_lookback_horizon:
  desc: null
  value: 1
rollout_fragment_length:
  desc: null
  value: auto
batch_mode:
  desc: null
  value: truncate_episodes
compress_observations:
  desc: null
  value: false
remote_worker_envs:
  desc: null
  value: false
remote_env_batch_wait_ms:
  desc: null
  value: 0
enable_tf1_exec_eagerly:
  desc: null
  value: false
sample_collector:
  desc: null
  value: ray.rllib.evaluation.collectors.simple_list_collector.SimpleListCollector
preprocessor_pref:
  desc: null
  value: deepmind
observation_filter:
  desc: null
  value: NoFilter
update_worker_filter_stats:
  desc: null
  value: true
use_worker_filter_stats:
  desc: null
  value: true
enable_connectors:
  desc: null
  value: true
sampler_perf_stats_ema_coef:
  desc: null
  value: null
num_learners:
  desc: null
  value: 0
num_gpus_per_learner:
  desc: null
  value: 0
num_cpus_per_learner:
  desc: null
  value: 1
local_gpu_idx:
  desc: null
  value: 0
gamma:
  desc: null
  value: 0.99
lr:
  desc: null
  value: 0.0001
grad_clip:
  desc: null
  value: null
grad_clip_by:
  desc: null
  value: global_norm
train_batch_size:
  desc: null
  value: 4000
train_batch_size_per_learner:
  desc: null
  value: null
model:
  desc: null
  value:
    _disable_preprocessor_api: false
    _disable_action_flattening: false
    fcnet_hiddens:
    - 256
    - 256
    fcnet_activation: tanh
    fcnet_weights_initializer: null
    fcnet_weights_initializer_config: null
    fcnet_bias_initializer: null
    fcnet_bias_initializer_config: null
    conv_filters: null
    conv_activation: relu
    conv_kernel_initializer: null
    conv_kernel_initializer_config: null
    conv_bias_initializer: null
    conv_bias_initializer_config: null
    conv_transpose_kernel_initializer: null
    conv_transpose_kernel_initializer_config: null
    conv_transpose_bias_initializer: null
    conv_transpose_bias_initializer_config: null
    post_fcnet_hiddens: []
    post_fcnet_activation: relu
    post_fcnet_weights_initializer: null
    post_fcnet_weights_initializer_config: null
    post_fcnet_bias_initializer: null
    post_fcnet_bias_initializer_config: null
    free_log_std: false
    no_final_linear: false
    vf_share_layers: false
    use_lstm: false
    max_seq_len: 20
    lstm_cell_size: 256
    lstm_use_prev_action: false
    lstm_use_prev_reward: false
    lstm_weights_initializer: null
    lstm_weights_initializer_config: null
    lstm_bias_initializer: null
    lstm_bias_initializer_config: null
    _time_major: false
    use_attention: false
    attention_num_transformer_units: 1
    attention_dim: 64
    attention_num_heads: 1
    attention_head_dim: 32
    attention_memory_inference: 50
    attention_memory_training: 50
    attention_position_wise_mlp_dim: 32
    attention_init_gru_gate_bias: 2.0
    attention_use_n_prev_actions: 0
    attention_use_n_prev_rewards: 0
    framestack: true
    dim: 84
    grayscale: false
    zero_mean: true
    custom_model: custom_cnn
    custom_model_config: {}
    custom_action_dist: null
    custom_preprocessor: null
    encoder_latent_dim: null
    always_check_shapes: false
    lstm_use_prev_action_reward: -1
    _use_default_native_models: -1
_learner_connector:
  desc: null
  value: null
add_default_connectors_to_learner_pipeline:
  desc: null
  value: true
learner_config_dict:
  desc: null
  value: {}
optimizer:
  desc: null
  value: {}
max_requests_in_flight_per_sampler_worker:
  desc: null
  value: 2
_learner_class:
  desc: null
  value: null
explore:
  desc: null
  value: true
exploration_config:
  desc: null
  value:
    type: StochasticSampling
algorithm_config_overrides_per_module:
  desc: null
  value: {}
_per_module_overrides:
  desc: null
  value: {}
count_steps_by:
  desc: null
  value: env_steps
policy_map_capacity:
  desc: null
  value: 100
policy_mapping_fn:
  desc: null
  value: <function get_policy_mapping_fn at 0x3b35d7670>
policies_to_train:
  desc: null
  value: null
policy_states_are_swappable:
  desc: null
  value: false
observation_fn:
  desc: null
  value: null
input_read_method:
  desc: null
  value: read_parquet
input_read_method_kwargs:
  desc: null
  value: {}
input_read_schema:
  desc: null
  value: {}
map_batches_kwargs:
  desc: null
  value: {}
iter_batches_kwargs:
  desc: null
  value: {}
prelearner_class:
  desc: null
  value: null
prelearner_module_synch_period:
  desc: null
  value: 10
dataset_num_iters_per_learner:
  desc: null
  value: null
input_config:
  desc: null
  value: {}
actions_in_input_normalized:
  desc: null
  value: false
postprocess_inputs:
  desc: null
  value: false
shuffle_buffer_size:
  desc: null
  value: 0
output:
  desc: null
  value: null
output_config:
  desc: null
  value: {}
output_compress_columns:
  desc: null
  value:
  - obs
  - new_obs
output_max_file_size:
  desc: null
  value: 67108864
offline_sampling:
  desc: null
  value: false
evaluation_interval:
  desc: null
  value: null
evaluation_duration:
  desc: null
  value: 10
evaluation_duration_unit:
  desc: null
  value: episodes
evaluation_sample_timeout_s:
  desc: null
  value: 120.0
evaluation_parallel_to_training:
  desc: null
  value: false
evaluation_force_reset_envs_before_iteration:
  desc: null
  value: true
evaluation_config:
  desc: null
  value: null
off_policy_estimation_methods:
  desc: null
  value: {}
ope_split_batch_by_episode:
  desc: null
  value: true
evaluation_num_env_runners:
  desc: null
  value: 0
in_evaluation:
  desc: null
  value: false
sync_filters_on_rollout_workers_timeout_s:
  desc: null
  value: 10.0
keep_per_episode_custom_metrics:
  desc: null
  value: false
metrics_episode_collection_timeout_s:
  desc: null
  value: 60.0
metrics_num_episodes_for_smoothing:
  desc: null
  value: 100
min_time_s_per_iteration:
  desc: null
  value: null
min_train_timesteps_per_iteration:
  desc: null
  value: 0
min_sample_timesteps_per_iteration:
  desc: null
  value: 0
export_native_model_files:
  desc: null
  value: false
checkpoint_trainable_policies_only:
  desc: null
  value: false
logger_creator:
  desc: null
  value: null
logger_config:
  desc: null
  value: null
log_level:
  desc: null
  value: WARN
log_sys_usage:
  desc: null
  value: true
fake_sampler:
  desc: null
  value: false
seed:
  desc: null
  value: null
_run_training_always_in_thread:
  desc: null
  value: false
_evaluation_parallel_to_training_wo_thread:
  desc: null
  value: false
ignore_env_runner_failures:
  desc: null
  value: false
recreate_failed_env_runners:
  desc: null
  value: false
max_num_env_runner_restarts:
  desc: null
  value: 1000
delay_between_env_runner_restarts_s:
  desc: null
  value: 60.0
restart_failed_sub_environments:
  desc: null
  value: false
num_consecutive_env_runner_failures_tolerance:
  desc: null
  value: 100
env_runner_health_probe_timeout_s:
  desc: null
  value: 30
env_runner_restore_timeout_s:
  desc: null
  value: 1800
_model_config_dict:
  desc: null
  value: {}
_rl_module_spec:
  desc: null
  value: null
_AlgorithmConfig__prior_exploration_config:
  desc: null
  value: null
_tf_policy_handles_more_than_one_loss:
  desc: null
  value: false
_disable_preprocessor_api:
  desc: null
  value: false
_disable_action_flattening:
  desc: null
  value: false
_disable_initialize_loss_from_dummy_batch:
  desc: null
  value: false
_dont_auto_sync_env_runner_states:
  desc: null
  value: false
simple_optimizer:
  desc: null
  value: true
policy_map_cache:
  desc: null
  value: -1
worker_cls:
  desc: null
  value: -1
synchronize_filters:
  desc: null
  value: -1
enable_async_evaluation:
  desc: null
  value: -1
custom_async_evaluation_function:
  desc: null
  value: -1
_enable_rl_module_api:
  desc: null
  value: -1
auto_wrap_old_gym_envs:
  desc: null
  value: -1
disable_env_checking:
  desc: null
  value: -1
always_attach_evaluation_results:
  desc: null
  value: -1
replay_sequence_length:
  desc: null
  value: null
_disable_execution_plan_api:
  desc: null
  value: -1
lr_schedule:
  desc: null
  value: null
use_critic:
  desc: null
  value: true
use_gae:
  desc: null
  value: true
use_kl_loss:
  desc: null
  value: true
kl_coeff:
  desc: null
  value: 0.2
kl_target:
  desc: null
  value: 0.01
sgd_minibatch_size:
  desc: null
  value: 128
mini_batch_size_per_learner:
  desc: null
  value: null
num_sgd_iter:
  desc: null
  value: 30
shuffle_sequences:
  desc: null
  value: true
vf_loss_coeff:
  desc: null
  value: 1.0
entropy_coeff:
  desc: null
  value: 0.0
entropy_coeff_schedule:
  desc: null
  value: null
clip_param:
  desc: null
  value: 0.3
vf_clip_param:
  desc: null
  value: 10.0
vf_share_layers:
  desc: null
  value: -1
lambda:
  desc: null
  value: 1.0
input:
  desc: null
  value: sampler
policies:
  desc: null
  value:
    prey_policy:
    - null
    - Box(0, 1, (10, 10, 3), uint8)
    - Discrete(5)
    - {}
    predator_policy:
    - null
    - Box(0, 1, (10, 10, 3), uint8)
    - Discrete(5)
    - {}
create_env_on_driver:
  desc: null
  value: false
custom_eval_function:
  desc: null
  value: null
framework:
  desc: null
  value: torch
_wandb:
  desc: null
  value:
    python_version: 3.9.6
    cli_version: 0.17.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1724125769
    t:
      1:
      - 1
      - 30
      - 55
      2:
      - 1
      - 30
      - 55
      3:
      - 13
      - 14
      - 16
      - 19
      - 23
      4: 3.9.6
      5: 0.17.6
      8:
      - 4
      - 8
      13: darwin-arm64
trial_log_path:
  desc: null
  value: /tmp/ray/session_2024-08-20_09-19-10_120610_55104/artifacts/2024-08-20_09-19-11/prey_speed=1.2/driver_artifacts/PPO_custom_tag_v0_29348_00000_0_2024-08-20_09-19-11
__stdout_file__:
  desc: null
  value: null
__stderr_file__:
  desc: null
  value: null
trial_id:
  desc: null
  value: '29348_00000'
date:
  desc: null
  value: 2024-08-20_09-22-05
pid:
  desc: null
  value: 55209
hostname:
  desc: null
  value: Joys-MacBook-Pro.local
node_ip:
  desc: null
  value: 127.0.0.1
